[accessibility]
ui_scale = 1.1500000096857548

[bar.default]
background_opacity = 0.84999998100101948
center = [ "audio_visualizer" ]
end = [ "media", "clipboard", "network", "bluetooth", "group:g1", "battery", "control-center", "session" ]
padding = 15
scale = 1.2500000111758709
start = [ "launcher", "clock", "workspaces", "tray", "recorder", "widget", "gamermode", "cat" ]
thickness = 33

    [bar.default.dead_zone.actions]
    right = "none"

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "toggle", "volume" ]
    opacity = 1.0
    padding = 6.0

[brightness]
sync_all_monitors = true

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 272.0
    box_width = 496.0
    cx = 344.0
    cy = 1416.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        background_opacity = 0.0
        clock_style = "digital"
        color = "on_surface"
        font_family = ""

[dock]
auto_hide = true
icon_size = 16
launcher_position = "start"
position = "left"

[hot_corners.top_left]
action = "control_center"

[location]
address = "Sherbrooke, QC"
latitude = 45.400100000000002
longitude = 71.899100000000004

[lockscreen]
blur_intensity = 0.50999998860061169
fingerprint = false
wallpaper = "/home/alexy/Pictures/Wallpapers/planets.jpg"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 957.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.75
        background_radius = 12.0
        center_password_text = true
        input_opacity = 0.75
        input_radius = 15.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 176.0
    box_width = 448.0
    cx = 1280.0
    cy = 768.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

[plugin_settings."cleboost/hotspot"]
interface = "wlo1"
password = "Alexy_Sharing_9384"
ssid = "Alexy's PC"

[plugin_settings."dotnetrob/cat"]
panel_placement = "floating"

[plugin_settings."noctalia/bitwarden"]
gen_special = true

[plugin_settings."noctalia/mpvpaper"]
picker_placement = "floating"
picker_position = "center"
video_directory = "/home/alexy/Wallpapers"

[plugin_settings."yocraft/web-launcher"]
icon_provider = "duckduckgo"

[plugins]
enabled = [
    "noctalia/bitwarden",
    "yocraft/web-launcher",
    "cleboost/ssh-launcher",
    "noctalia/screen_recorder",
    "avivbintangaringga/nix-monitor",
    "dotnetrob/cat",
    "cleboost/hotspot",
    "noctalia/mpvpaper",
    "oldirtty/color_picker",
    "nomadcxx/gamer-mode",
    "radimous/prismlauncher-instances"
]

[shell]
avatar_path = "/home/alexy/.config/nixos/hosts/laptop/profile-picture.jpg"
corner_radius_scale = 1.2500000186264515
lang = "en"

    [shell.launcher]
    auto_paste = "ctrl_v"

        [shell.launcher.providers.calculator]
        global = true

        [shell.launcher.providers.emoji]
        global = false

        [shell.launcher.providers.session]
        prefix = ""

        [shell.launcher.providers.wallpaper]
        global = false
        prefix = ""

        [shell.launcher.providers.windows]
        prefix = ""

    [shell.panel]
    control_center_placement = "floating"
    floating_layer = "top"
    open_near_click_session = false
    transparency_mode = "soft"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [shell.screen_corners]
    enabled = true
    size = 19

    [shell.screenshot]
    directory = "/home/alexy/Pictures/Screenshots"

    [shell.shadow]
    alpha = 0.53999998793005943

[theme]
builtin = "Kanagawa"
community_palette = "Cream"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "hyprland", "kitty", "starship" ]
    community_ids = [ "zen-browser", "discord", "neovim", "obsidian", "lazygit", "yazi" ]
    enable_builtin_templates = true
    enable_community_templates = true

[wallpaper]
directory = "/home/alexy/Wallpapers"
directory_dark = "/home/alexy/Wallpapers"
directory_light = "/home/alexy/Wallpapers"
enabled = true
transition = [ "disc" ]

    [wallpaper.default]
    path = "/home/alexy/Wallpapers/room1-sunset.png"

    [wallpaper.last]
    path = "/home/alexy/Wallpapers/room1-sunset.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/alexy/Wallpapers/room1-sunset.png"

[widget.audio_visualizer]
anchor = true
show_when_idle = true
width = 150

    [widget.audio_visualizer.actions]
    left = "panel-toggle control-center home"
    middle = "none"
    right = "volume-mute"

[widget.bar]
enabled = false
type = "yuuto/calculator:bar"

[widget.bar_2]
type = "icefish/phone-connect:bar"

[widget.cat]
type = "dotnetrob/cat:cat"

[widget.clock.actions]
middle = "none"

[widget.gamermode]
type = "nomadcxx/gamer-mode:gamermode"

[widget.nix-monitor]
enabled = false
scale = 0.75
type = "avivbintangaringga/nix-monitor:nix-monitor"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.special-workspaces]
type = "jamesfeeder/special-workspaces:special-workspaces"

[widget.toggle]
type = "cleboost/hotspot:toggle"

[widget.widget]
type = "oldirtty/color_picker:widget"

[widget.workspaces]
hide_when_empty = true
style = "focus_hint"
