{
  lib,
  pkgs,
  ...
}: let
  themeSync = pkgs.writeShellApplication {
    name = "theme-sync";
    runtimeInputs = [pkgs.jq];
    text = ''
      set -euo pipefail
      COLORS_JSON="$HOME/.local/state/serpantinum/qs_matugen_colors.json"
      HYPR_OUT="$HOME/.config/hypr/colors.conf"
      GHOSTTY_OUT="$HOME/.config/ghostty/config-colors"
      KITTY_OUT="$HOME/.config/kitty/colors-live.conf"
      KITTY_CONF="$HOME/.config/kitty/kitty.conf"
      BTOP_OUT="$HOME/.config/btop/themes/matugen.theme"
      YAZI_OUT="$HOME/.config/yazi/theme.toml"
      mkdir -p "$(dirname "$HYPR_OUT")" "$(dirname "$GHOSTTY_OUT")" \
        "$(dirname "$KITTY_OUT")" "$(dirname "$BTOP_OUT")" "$(dirname "$YAZI_OUT")"

      get() {
        local v
        v=$(jq -r --arg k "$1" '.[$k] // empty' "$COLORS_JSON")
        if [ -z "$v" ]; then
          echo "theme-sync: warning: missing color key '$1', falling back to 000000" >&2
          v="#000000"
        fi
        echo "''${v#\#}"
      }

      # --- Hyprland ---
      jq -r 'to_entries[] | "$\(.key) = rgb(\(.value | ltrimstr("#")))"' "$COLORS_JSON" > "$HYPR_OUT"

      # --- Ghostty ---
      {
        echo "background = $(get base)"
        echo "foreground = $(get text)"
        echo "cursor-color = $(get text)"
        echo "selection-background = $(get surface1)"
        echo "selection-foreground = $(get text)"
        echo "palette = 0=#$(get crust)"
        echo "palette = 1=#$(get red)"
        echo "palette = 2=#$(get green)"
        echo "palette = 3=#$(get yellow)"
        echo "palette = 4=#$(get blue)"
        echo "palette = 5=#$(get mauve)"
        echo "palette = 6=#$(get teal)"
        echo "palette = 7=#$(get subtext1)"
        echo "palette = 8=#$(get surface2)"
        echo "palette = 9=#$(get red)"
        echo "palette = 10=#$(get green)"
        echo "palette = 11=#$(get yellow)"
        echo "palette = 12=#$(get sapphire)"
        echo "palette = 13=#$(get pink)"
        echo "palette = 14=#$(get teal)"
        echo "palette = 15=#$(get text)"
      } > "$GHOSTTY_OUT"

      # --- Kitty ---
      {
        echo "background #$(get base)"
        echo "foreground #$(get text)"
        echo "cursor #$(get text)"
        echo "selection_background #$(get surface1)"
        echo "selection_foreground #$(get text)"
        echo "color0  #$(get crust)"
        echo "color8  #$(get surface2)"
        echo "color1  #$(get red)"
        echo "color9  #$(get red)"
        echo "color2  #$(get green)"
        echo "color10 #$(get green)"
        echo "color3  #$(get yellow)"
        echo "color11 #$(get yellow)"
        echo "color4  #$(get blue)"
        echo "color12 #$(get sapphire)"
        echo "color5  #$(get mauve)"
        echo "color13 #$(get pink)"
        echo "color6  #$(get teal)"
        echo "color14 #$(get teal)"
        echo "color7  #$(get subtext1)"
        echo "color15 #$(get text)"
      } > "$KITTY_OUT"

      # --- btop ---
      {
        echo "# Auto-generated by theme-sync from matugen colors. Do not edit by hand."
        echo "theme[main_bg]=\"#$(get base)\""
        echo "theme[main_fg]=\"#$(get text)\""
        echo "theme[title]=\"#$(get text)\""
        echo "theme[hi_fg]=\"#$(get mauve)\""
        echo "theme[selected_bg]=\"#$(get surface1)\""
        echo "theme[selected_fg]=\"#$(get text)\""
        echo "theme[inactive_fg]=\"#$(get surface2)\""
        echo "theme[graph_text]=\"#$(get subtext1)\""
        echo "theme[proc_misc]=\"#$(get teal)\""
        echo "theme[cpu_box]=\"#$(get surface2)\""
        echo "theme[mem_box]=\"#$(get surface2)\""
        echo "theme[net_box]=\"#$(get surface2)\""
        echo "theme[proc_box]=\"#$(get surface2)\""
        echo "theme[div_line]=\"#$(get surface1)\""
        echo "theme[temp_start]=\"#$(get green)\""
        echo "theme[temp_mid]=\"#$(get yellow)\""
        echo "theme[temp_end]=\"#$(get red)\""
        echo "theme[cpu_start]=\"#$(get green)\""
        echo "theme[cpu_mid]=\"#$(get yellow)\""
        echo "theme[cpu_end]=\"#$(get red)\""
        echo "theme[free_start]=\"#$(get blue)\""
        echo "theme[free_mid]=\"#$(get sapphire)\""
        echo "theme[free_end]=\"#$(get mauve)\""
        echo "theme[cached_start]=\"#$(get teal)\""
        echo "theme[cached_mid]=\"#$(get sapphire)\""
        echo "theme[cached_end]=\"#$(get blue)\""
        echo "theme[available_start]=\"#$(get green)\""
        echo "theme[available_mid]=\"#$(get yellow)\""
        echo "theme[available_end]=\"#$(get red)\""
        echo "theme[used_start]=\"#$(get blue)\""
        echo "theme[used_mid]=\"#$(get mauve)\""
        echo "theme[used_end]=\"#$(get pink)\""
        echo "theme[download_start]=\"#$(get green)\""
        echo "theme[download_mid]=\"#$(get teal)\""
        echo "theme[download_end]=\"#$(get blue)\""
        echo "theme[upload_start]=\"#$(get yellow)\""
        echo "theme[upload_mid]=\"#$(get pink)\""
        echo "theme[upload_end]=\"#$(get red)\""
        echo "theme[process_start]=\"#$(get blue)\""
        echo "theme[process_mid]=\"#$(get mauve)\""
        echo "theme[process_end]=\"#$(get red)\""
      } > "$BTOP_OUT"

      # --- yazi ---
      {
        echo "# Auto-generated by theme-sync from matugen colors. Do not edit by hand."
        echo ""
        echo "[manager]"
        echo "cwd = { fg = \"#$(get blue)\" }"
        echo "hovered = { fg = \"#$(get base)\", bg = \"#$(get mauve)\" }"
        echo "preview_hovered = { underline = true }"
        echo "find_keyword = { fg = \"#$(get yellow)\", italic = true }"
        echo "find_position = { fg = \"#$(get pink)\", bg = \"reset\", italic = true }"
        echo "marker_selected = { fg = \"#$(get green)\", bg = \"#$(get green)\" }"
        echo "marker_copied = { fg = \"#$(get yellow)\", bg = \"#$(get yellow)\" }"
        echo "marker_cut = { fg = \"#$(get red)\", bg = \"#$(get red)\" }"
        echo "border_symbol = \"│\""
        echo "border_style = { fg = \"#$(get surface1)\" }"
        echo ""
        echo "[status]"
        echo "separator_open = \"\""
        echo "separator_close = \"\""
        echo "separator_style = { fg = \"#$(get surface2)\", bg = \"#$(get surface2)\" }"
        echo "mode_normal = { fg = \"#$(get base)\", bg = \"#$(get blue)\", bold = true }"
        echo "mode_select = { fg = \"#$(get base)\", bg = \"#$(get green)\", bold = true }"
        echo "mode_unset = { fg = \"#$(get base)\", bg = \"#$(get red)\", bold = true }"
        echo "progress_label = { fg = \"#$(get text)\", bold = true }"
        echo "progress_normal = { fg = \"#$(get blue)\", bg = \"#$(get surface1)\" }"
        echo "progress_error = { fg = \"#$(get red)\", bg = \"#$(get surface1)\" }"
        echo "permissions_t = { fg = \"#$(get green)\" }"
        echo "permissions_r = { fg = \"#$(get yellow)\" }"
        echo "permissions_w = { fg = \"#$(get red)\" }"
        echo "permissions_x = { fg = \"#$(get teal)\" }"
        echo "permissions_s = { fg = \"#$(get surface2)\" }"
        echo ""
        echo "[input]"
        echo "border = { fg = \"#$(get mauve)\" }"
        echo "title = { fg = \"#$(get text)\" }"
        echo "value = { fg = \"#$(get text)\" }"
        echo "selected = { reversed = true }"
        echo ""
        echo "[select]"
        echo "border = { fg = \"#$(get mauve)\" }"
        echo "active = { fg = \"#$(get pink)\" }"
        echo "inactive = { fg = \"#$(get subtext1)\" }"
        echo ""
        echo "[tabs]"
        echo "active = { fg = \"#$(get base)\", bg = \"#$(get mauve)\" }"
        echo "inactive = { fg = \"#$(get subtext1)\", bg = \"#$(get surface1)\" }"
        echo "sep_inner = { open = \"\", close = \"\" }"
        echo "sep_outer = { open = \"\", close = \"\" }"
        echo ""
        echo "[which]"
        echo "mask = { bg = \"#$(get base)\" }"
        echo "cand = { fg = \"#$(get teal)\" }"
        echo "rest = { fg = \"#$(get subtext1)\" }"
        echo "desc = { fg = \"#$(get pink)\" }"
        echo "separator_style = { fg = \"#$(get surface2)\" }"
      } > "$YAZI_OUT"

      # --- live reload ---
      hyprctl reload >/dev/null 2>&1 || true
      systemctl reload --user app-com.mitchellh.ghostty.service 2>/dev/null \
        || pkill -SIGUSR2 ghostty 2>/dev/null || true
      touch "$KITTY_CONF" 2>/dev/null || true
      pkill -SIGUSR1 kitty 2>/dev/null || true
      # btop has no reliable live-reload signal; if it's running with the
      # matugen theme already selected, this nudges it to re-read on next
      # redraw on some builds, but a manual theme reselect/restart is the
      # only guaranteed way to pick up palette changes.
      pkill -SIGUSR1 btop 2>/dev/null || true
      # yazi picks up theme.toml changes automatically on next redraw,
      # no signal needed.
    '';
  };
in {
  home.activation.themeSync = lib.hm.dag.entryAfter ["writeBoundary"] ''
    $DRY_RUN_CMD ${themeSync}/bin/theme-sync || true
  '';
  systemd.user.services.theme-sync = {
    Unit.Description = "Regenerate Hyprland/Ghostty/Kitty/btop/yazi colors from matugen JSON";
    Service = {
      Type = "oneshot";
      ExecStart = "${themeSync}/bin/theme-sync";
    };
  };
  systemd.user.paths.theme-sync = {
    Unit.Description = "Watch matugen colors.json";
    Path.PathModified = "%h/.local/state/serpantinum/qs_matugen_colors.json";
    Install.WantedBy = ["default.target"];
  };
}
